---

mongodb_enabled: yes
mongodb_packages:
  - python-selinux
  - python-pymongo
  - mongodb-org

mongodb_conf:
  auth: "false"
  bind_ip: 127.0.0.1
  cpu: "true"
  dbpath: /var/lib/mongodb/
  # diaglog: 0 # deprecated
  logappend: "true"
  logpath: /var/log/mongodb/mongod.log
  noauth: "true"
  nohints: "false"
  nohttpinterface: "false"
  nojournal: "true"
  noprealloc: "false"
  noscripting: "false"
  notablescan: "false"
  objcheck: "false"
  port: 27017
  quota: "false"
  # replSet: "" # Set for enable replication
  verbose: "true"
  vvvv: "true"


# Log rotation
mongodb_logrotate: yes                             # Rotate mongodb logs.
mongodb_logrotate_options:
  - compress
  - copytruncate
  - daily
  - dateext
  - rotate 7
  - size 10M
