---
# This is main tasks file for mysql role
# filename: roles/mysql/tasks/main.yml
# Load vars specific to OS Family.

#- include_vars: "{{ ansible_os_family }}.yaml"
#  when: ansible_os_family != 'Debian'

- include: install_Redhat.yaml
  when: ansible_os_family == 'RedHat'

- include: install_Debian.yaml
  when: ansible_os_family == 'Debian'

- include: configure.yaml
- include: service.yaml
