---
# Playbook for Database Servers
# filename: db.yml
- hosts: security_group_dbservers
  remote_user: ubuntu
  sudo: yes
  roles:
     #- { role: mysql, mysql_bind: "{{ ansible_eth0.ipv4.address }}" }
     - {role: mtpereira.mongodb }
