---
# task: main.yaml

# essential tasks
- name: creating devops group
  group: name=devops state=present
- name: create devops user
  user: name=devops comment="Devops User" uid=2001 group=devops
- name: install htop package
  action: apt name=htop state=present update_cache=yes
   
   
