---

- hosts: all
  remote_user: ubuntu
  sudo: yes
  tasks:
      - group: name=devops state=present
      - name: create devops user with admin previleges
        user: name=devops comment="Devops User" uid=2001 group=devops
        
      - name: install htop package
        action: apt name=htop state=present update_cache=yes
        
        