---

dependencies: []

galaxy_info:
  author: klen
  company: Stouts
  description: Manage mongodb
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - wheezy
  categories:
  - database:nosql
