---

- name: Add APT key
  apt_key: url=http://docs.mongodb.org/10gen-gpg-key.asc id=7F0CEB10

- name: Add APT repository (Ubuntu)
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' update_cache=yes
  when: ansible_distribution == 'Ubuntu'

- name: Add APT repository (Debian)
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' update_cache=yes
  when: ansible_distribution == 'Debian'

- name: Install mongodb-org
  apt: pkg={{item}}
  with_items: mongodb_packages
