---
# configure Docker service

- name: start docker and ensure it runs after boot
  service: name=docker state=started enabled=yes
      
- name: insert ubuntu on docker
  user: name=ubuntu groups=docker 

- name: change dns used by docker containers
  lineinfile: dest=/etc/default/docker regexp='^DOCKER_OPTS' line='DOCKER_OPTS="--dns {{ ansible_dns }}"'
  notify:
  - restart docker





